export const text = {
  name: 'GetMovies',
  mainTitle: 'Get The Best Movies on GetMovies',
  movies: 'Movies',
  favourites: 'Favourites',
  signIn: 'Sign In',
  signUp: 'Sign Up',
  signOut: 'Sign Out',
  colorMode: 'Color Mode',
  goodReviews: 'Good Reviews',
  kinopoiskRating: 'Rating Kinopoisk',
  userRating: 'User Rating',
  kinopubRating: 'Rating Kinopub',
  createdBy: 'Created by Ivanov',
  haveAccount: 'Already have an account?',
  noAccount: 'Do not have an account?',
  showMore: 'Show more',
  confirmationRequiredError: 'Confirmation is required',
  passwordMismatchError: 'Password mismatch',
  passwordRequiredError: 'Password is required',
  passwordMinLengthError: 'Password minimum length is 6 symbols',
  usernameRequiredError: 'Username is required',
  emailRequiredError: 'Email is required',
  emailPatternError: 'Must be an email'
};
